/// Flutter icons Tractian
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Tractian
///      fonts:
///       - asset: fonts/Tractian.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

class Tractian {
  Tractian._();

  static const _kFontFam = 'Tractian';
  static const String? _kFontPkg = null;

  static const IconData component =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData asset =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
